name: Daily Crawler

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 00:00 KST (UTC 기준 15:00)
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 크롤러 실행
        run: python crawler.py
